### ISSUE TITLE
README shows unsupported feature to prevent manual promotion in pipeline

### ISSUE THREAD

**Issue by aratno** [renderedtext/when#10]
The README shows support for an "allow" field [here](https://github.com/renderedtext/when#allow-manual-promotion-only-on-master-branch), but this appears unsupported in the `semaphore.yml` file. When I tried including this:
```
- name: Deploy to Production
  pipeline_file: deploy_to_production.yml
  allow:
    when: "branch = 'master'"
```

I got this error in the web UI for the running pipeline:
```
Error: [{"Schema does not allow additional properties.", "#/promotions/1/allow"}]
```

Is this feature supported or not?
